name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Build GRPC
      working-directory: ./sort_skeleton/sort/make grpc-compile
      run: make grpc-compile

    - name: Build
      working-directory: ./sort_skeleton/sort/sorting-service
      run: go build -v ./...


    - name: Test
      run: go test -v ./...
